name: run

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: composer update
      run: composer update
    - name: test
      run: php -f test.php -- --runs 3
    - name: test old EasyRdf
      run: php -f testOldReleases.php
