name: run

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: composer update
      run: composer update
    - name: test
      run: php -f test.php
    - name: test old EasyRdf
      run: php -f testOldReleases.php
