name: run

on: push

jobs:
  small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: composer update
      run: composer update
    - name: test
      run: php -f test.php -- --data data/small --runs 10 | tee data-small.json
    - name: test old EasyRdf
      run: php -f testOldReleases.php -- --data data/small --runs 10 | tee data-small-old.json
    - name: store artifacts
      uses: actions/upload-artifact@v2
      with:
        name: small-test-results
        path: data-*.json
#  medium:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: shivammathur/setup-php@v2
#      with:
#        php-version: '7.4'
#    - name: composer update
#      run: composer update
#    - name: test
#      run: php -f test.php -- --data data/medium --runs 1 | tee data-medium.json
#    - name: test old EasyRdf
#      run: php -f testOldReleases.php -- --data data/medium --runs 1 | tee data-medium-old.json
#    - name: plots
#      run: Rscript plots.R
#    - name: store artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: medium-test-results
#        path: data-*.json
#  big:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: shivammathur/setup-php@v2
#      with:
#        php-version: '7.4'
#    - name: composer update
#      run: composer update
#    - name: test
#      run: php -f test.php -- --data data/big --runs 1 | tee data-big.json
#    - name: test old EasyRdf
#      run: php -f testOldReleases.php -- --data data/big --runs 1 | tee data-big-old.json
#    - name: store artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: big-test-results
#        path: data-*.json
  charts:
    needs:
    - small
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cache R packages
      uses: actions/cache@v2
      with:
        path: ~/R
        key: R
    - uses: actions/download-artifact@master
      with:
        name: small-test-results
    - run: ls -1
#    - name: plots
#      run: Rscript plots.R
#    - name: store artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: charts
#        path: "*.svg"
      